### ISSUE TITLE
Unable to load integration in HA 2026.5.0

### ISSUE THREAD

**Issue by cregeland** [basbruss/adaptive-cover#449]
### What version of Adaptive Cover are you using?

1.4.5

### What version of Home Assistant are you using?

2026.5.0

### Checklist

- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Integration will not start after updating to 2026.5.0. 2 errors in log:

Logger: homeassistant.setup
Source: setup.py:343
First occurred: 18:15:08 (1 occurrence)
Last logged: 18:15:08

Setup failed for custom integration 'adaptive_cover': Unable to import component: cannot import name 'state_attr' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1024, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 86, in run
    result = ctx.run(self.task)
  File "/usr/local/lib/python3.14/concurrent/futures/thread.py", line 73, in run
    return fn(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1084, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/adaptive_cover/__init__.py", line 20, in <module>
    from .coordinator import AdaptiveDataUpdateCoordinator
  File "/config/custom_components/adaptive_cover/coordinator.py", line 26, in <module>
    from homeassistant.helpers.template import state_attr
ImportError: cannot import name 'state_attr' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1044, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1036, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1084, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/adaptive_cover/__init__.py", line 20, in <module>
    from .coordinator import AdaptiveDataUpdateCoordinator
  File "/config/custom_components/adaptive_cover/coordinator.py", line 26, in <module>
    from homeassistant.helpers.template import state_attr
ImportError: cannot import name 'state_attr' from 'homeassistant.helpers.template' (/usr/src/homeassistant/homeassistant/helpers/template/__init__.py)


And second:

Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 18:15:08 (1 occurrence)
Last logged: 18:15:08

Detected blocking call to import_module with args ('custom_components.adaptive_cover',) in /usr/src/homeassistant/homeassistant/loader.py, line 1084: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.14/asyncio/base_events.py", line 706, in run_until_complete self.run_forever() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 677, in run_forever self._run_once() File "/usr/local/lib/python3.14/asyncio/base_events.py", line 2046, in _run_once handle._run() File "/usr/local/lib/python3.14/asyncio/events.py", line 94, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 170, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 343, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1036, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1084, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)

### Reproduction steps

1.
2.
3.
...


### Diagnostics dump

_No response_

**Comment by k0rui** [comment]
The integration fails to load because this import no longer works:

```python
from homeassistant.helpers.template import state_attr
```

The affected files are:

```text
/config/custom_components/adaptive_cover/coordinator.py
/config/custom_components/adaptive_cover/calculation.py
```

I was able to work around the issue by removing that import from both files and adding the function `state_attr` directly after the imports:

```python
def state_attr(hass, entity_id: str, attr_name: str):
    state = hass.states.get(entity_id)
    if state is None:
        return None
    return state.attributes.get(attr_name)
```

After restarting Home Assistant, the integration loads correctly again.

Now if it will work correctly by doing this... that's to be seen. 

EDIT: I've done some quick tests and it seems to be working correctly.

**Comment by grouts112** [comment]
https://github.com/basbruss/adaptive-cover/issues/449#issuecomment-4390907313
Fixed it for me.
 havn't seen an official version update yet.

**Comment by davemunneke** [comment]
Fixed it for me as well.

**Comment by Jimfizz** [comment]
Fixed only one of my two configurations. I get this error for the first one : cannot convert float NaN to integer

Edit: works fine now

**Comment by cobraviola** [comment]
Fixed it for me.

**Comment by flecmart** [comment]
I investigated this and opened a pull request.

`state_attr` was refactored to a jinja extension in core. I suggest to call the hass state api directly and not depend on the jinja extension as we do not need the jinja overhead in this case.

**Comment by jacumal** [comment]
Is it possible get an update of adaptive cover, fixing that issue?

**Comment by jubepue** [comment]
Hi @basbruss, are you still maintaining the repository? Are you going to merge the PRs?

**Comment by DJKatastrof** [comment]
This fixed it for me as well. Thank you!!
