### ISSUE TITLE
Automation for horizontal screens from Somfy only works on HA reboot

### ISSUE THREAD

**Issue by tobiasnorbo** [basbruss/adaptive-cover#126]
### What version of Adaptive Cover are you using?

1.1.0

### What version of Home Assistant are you using?

12.2

### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

My awnings controlled by Somfy only runs this adaptive sover automation when I reboot HA. Since the minimum retractable setting is 1%, this also means, that when I reboot HA during the evening/night, then the screen opens to 1%, and I have to manually pull it back in.

### Reproduction steps

1. Reboot HA
2. Awnings go to the setting matching current time and other settings in my integration.
3. 
...

**Comment by basbruss** [comment]
@tobiasnorbo try v1.1.2. Is the control toggle switch on?

**Comment by tobiasnorbo** [comment]
I wish I could tell you for sure, but after updating to V1.1.2, I was not able to reload the configurations.

**Comment by basbruss** [comment]
Any logs? Need more information to debug it.

**Comment by tobiasnorbo** [comment]
I Hope this helps:

TypeError: get_safe_state() missing 1 required positional argument: 'entity_id'
2024-04-28 18:56:14.523 DEBUG (MainThread) [custom_components.adaptive_cover] Finished fetching adaptive_cover data in 0.003 seconds (success: False)
2024-04-28 18:56:19.292 WARNING (SyncWorker_49) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ddecad0>: Failed to establish a new connection: [Errno 113] Host is unreachable')': /upnp/control/insight1
2024-04-28 18:56:22.652 ERROR (Wemo Events Thread) [pywemo.ouimeaux_device] Unable to re-probe wemo <WeMo Insight "Printer"> at 192.168.1.181
2024-04-28 18:56:28.513 ERROR (Wemo Events Thread) [pywemo.ouimeaux_device] Unable to reconnect with Printer
2024-04-28 18:56:31.612 WARNING (Wemo Events Thread) [pywemo.subscribe] Resubscribe error for <Subscription basicevent "Printer"> (HTTPConnectionPool(host='192.168.1.181', port=49153): Max retries exceeded with url: /upnp/event/basicevent1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c365dc0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))), will retry in 60s
2024-04-28 18:56:43.580 WARNING (SyncWorker_49) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c365910>: Failed to establish a new connection: [Errno 113] Host is unreachable')': /upnp/control/insight1
2024-04-28 18:56:58.175 ERROR (Wemo Events Thread) [pywemo.ouimeaux_device] Unable to re-probe wemo <WeMo Insight "Printer"> at 192.168.1.181
2024-04-28 18:57:03.772 ERROR (Wemo Events Thread) [pywemo.ouimeaux_device] Unable to reconnect with Printer
2024-04-28 18:57:31.900 WARNING (SyncWorker_49) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5a621e50>: Failed to establish a new connection: [Errno 113] Host is unreachable')': /upnp/control/insight1
2024-04-28 18:57:34.738 ERROR (MainThread) [custom_components.adaptive_cover] Unexpected error fetching adaptive_cover data: get_safe_state() missing 1 required positional argument: 'entity_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/adaptive_cover/coordinator.py", line 225, in _async_update_data
    self.after_start_time
  File "/config/custom_components/adaptive_cover/coordinator.py", line 306, in after_start_time
    time = get_datetime_from_state(get_safe_state(self.start_time_entity))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by tobiasnorbo** [comment]
I Hope this helps:

TypeError: get_safe_state() missing 1 required positional argument: 'entity_id'
2024-04-28 18:56:14.523 DEBUG (MainThread) [custom_components.adaptive_cover] Finished fetching adaptive_cover data in 0.003 seconds (success: False)
  File "/config/custom_components/adaptive_cover/coordinator.py", line 225, in _async_update_data
    self.after_start_time
  File "/config/custom_components/adaptive_cover/coordinator.py", line 306, in after_start_time
    time = get_datetime_from_state(get_safe_state(self.start_time_entity))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


I am not really familiar with reading these myself, so tried to delete whatever did not matter to the adaptive cover integration. I hope I added enough.

**Comment by basbruss** [comment]
I added a bugfix for the error you posted related to the start time entity.

**Comment by tobiasnorbo** [comment]
Thanks, but I am not able to load it now.

Logger: homeassistant.setup
Source: setup.py:316
First occurred: 21:49:38 (1 occurrences)
Last logged: 21:49:38

Setup failed for custom integration 'adaptive_cover': Unable to import component: cannot import name 'EventStateChangedData' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 979, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/adaptive_cover/__init__.py", line 19, in <module>
    from .coordinator import AdaptiveDataUpdateCoordinator
  File "/config/custom_components/adaptive_cover/coordinator.py", line 16, in <module>
    from homeassistant.core import Event, EventStateChangedData, HomeAssistant, State
ImportError: cannot import name 'EventStateChangedData' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 316, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 997, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 989, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/adaptive_cover/__init__.py", line 19, in <module>
    from .coordinator import AdaptiveDataUpdateCoordinator
  File "/config/custom_components/adaptive_cover/coordinator.py", line 16, in <module>
    from homeassistant.core import Event, EventStateChangedData, HomeAssistant, State
ImportError: cannot import name 'EventStateChangedData' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

**Comment by basbruss** [comment]
@tobiasnorbo Fixed with https://github.com/basbruss/adaptive-cover/releases/tag/v1.1.3-hotfix
I added some code already to the release which only works with the future HA release

**Comment by tobiasnorbo** [comment]
Thanks a lot. It finally worked!Den 28. apr. 2024 kl. 22.40 skrev BasBruss ***@***.***>:﻿
@tobiasnorbo Fixed with https://github.com/basbruss/adaptive-cover/releases/tag/v1.1.3-hotfix
I added some code already to the release which only works with the future HA release
